const languages = [
  { code: "tr", longCode: "tr-TR", name: "Türkçe" },
  { code: "en", longCode: "en-US", name: "English" },
  { code: "de", longCode: "de-DE", name: "Deutsch" },
  { code: "fr", longCode: "fr-FR", name: "Français" },
  { code: "es", longCode: "es-ES", name: "Español" },
  { code: "it", longCode: "it-IT", name: "Italiano" },
  { code: "ru", longCode: "ru-RU", name: "Русский" },
  { code: "ar", longCode: "ar-AR", name: "العربية" },
  { code: "zh", longCode: "zh-ZH", name: "中文" },
  { code: "ja", longCode: "ja-JA", name: "日本語" },
  { code: "ko", longCode: "ko-KO", name: "한국어" },
  { code: "pt", longCode: "pt-PT", name: "Português" },
  { code: "hi", longCode: "hi-HI", name: "Hindi" },
  { code: "bn", longCode: "bn-BN", name: "Bengali" },
  { code: "id", longCode: "id-ID", name: "Bahasa Indonesia" },
  { code: "ms", longCode: "ms-MS", name: "Bahasa Melayu" },
  { code: "fa", longCode: "fa-FA", name: "فارسی" },
  { code: "vi", longCode: "vi-VI", name: "Tiếng Việt" },
  { code: "th", longCode: "th-TH", name: "ภาษาไทย" },
  { code: "nl", longCode: "nl-NL", name: "Nederlands" },
  { code: "pl", longCode: "pl-PL", name: "Polski" },
  { code: "sv", longCode: "sv-SV", name: "Svenska" },
  { code: "no", longCode: "no-NO", name: "Norsk" },
  { code: "da", longCode: "da-DA", name: "Dansk" },
  { code: "fi", longCode: "fi-FI", name: "Suomi" },
  { code: "cs", longCode: "cs-CS", name: "Čeština" },
  { code: "hu", longCode: "hu-HU", name: "Magyar" },
  { code: "el", longCode: "el-EL", name: "Ελληνικά" },
  { code: "ro", longCode: "ro-RO", name: "Română" },
  { code: "sk", longCode: "sk-SK", name: "Slovenčina" },
  { code: "uk", longCode: "uk-UK", name: "Українська" },
  { code: "hr", longCode: "hr-HR", name: "Hrvatski" }
];
